### ISSUE TITLE
你好，有考虑把这个加前端，直接做成实时的吗？

### ISSUE THREAD

**Issue by pren1** [taseikyo/gachi#2]
你好，请问你有考虑把这个直接做成实时的吗？后端用mongodb(pymongo), 前端用vue(或者别的什么框架）。这里有个很类似的系统，实时采集弹幕，实时分析。不过是专门给同传man做的：https://huolonglive.com/ 
如果普及到所有DD，想必会更有趣吧（

**Comment by taseikyo** [comment]
> 你好，请问你有考虑把这个直接做成实时的吗？后端用mongodb(pymongo), 前端用vue(或者别的什么框架）。这里有个很类似的系统，实时采集弹幕，实时分析。不过是专门给同传man做的：https://huolonglive.com/
> 如果普及到所有DD，想必会更有趣吧（

把 DD 公开处刑确实是个不错的想法（大雾）
不过目前我可能做不来，一方面申请域名买服务器太麻烦了（懒）；另一方面现在我可能没时间去做一个持续的维护

话说你们已经有展示同传相关数据的模板，把 DD 的数据加进去应该也不难吧，可能就是各方面指标和展示的数据不同？

**Comment by pren1** [comment]
> > 你好，请问你有考虑把这个直接做成实时的吗？后端用mongodb(pymongo), 前端用vue(或者别的什么框架）。这里有个很类似的系统，实时采集弹幕，实时分析。不过是专门给同传man做的：https://huolonglive.com/
> > 如果普及到所有DD，想必会更有趣吧（
> 
> 把 DD 公开处刑确实是个不错的想法（大雾）
> 不过目前我可能做不来，一方面申请域名买服务器太麻烦了（懒）；另一方面现在我可能没时间去做一个持续的维护
> 
> 话说你们已经有展示同传相关数据的模板，把 DD 的数据加进去应该也不难吧，可能就是各方面指标和展示的数据不同？

应该不难......但是我也没时间+懒（呆
毕竟没有人能全职做这些......
还是摸了（逃
